### PR TITLE
Add helper class to connect to google cloud postgres

### PR DESCRIPTION
**Pull request by brandantck**
Add helper class PostgresGCP that does a ssh tunnel to google cloud vm and binds google cloud postgres port to the local machine, allowing connection to google cloud postgres from local machine.

### CODE REVIEW

**Comment by hamcheezee** [comment]
Hi,

I’ve reviewed your code and have a question regarding `GCP_VM_PKEY_PATH`. Could you please confirm if the private key file needs to be copied to the VM path before making this change? I’m currently addressing this issue but encountering some warnings and would appreciate your guidance. Please see the attached picture for details.

Thank you!

Screenshot 2567-09-17 at 21 55 09

**Comment by hamcheezee** [comment]
> Hi [hamcheezee](https://github.com/hamcheezee),
> 
> @satish-a0 should have already added the private key file into the GCP VM, so you dont have to add it yourself. Can double check if the value of `GCP_VM_PKEY_PATH` for you is the full path pointing to your private key?
> 
> For example in my case, my value is: `GCP_VM_PKEY_PATH=/home/brandan/.ssh/brandan.t`

Sorry, I haven’t seen the private key file yet T_T. 
I’ll check with Satish tomorrow to make sure everything is in place. Thanks! 😊

Screenshot 2567-09-17 at 23 38 43

**Comment by brandantck** [comment]
> > Hi [hamcheezee](https://github.com/hamcheezee),
> > @satish-a0 should have already added the private key file into the GCP VM, so you dont have to add it yourself. Can double check if the value of `GCP_VM_PKEY_PATH` for you is the full path pointing to your private key?
> > For example in my case, my value is: `GCP_VM_PKEY_PATH=/home/brandan/.ssh/brandan.t`
> 
> Sorry, I haven’t seen the private key file yet T_T. I’ll check with Satish tomorrow to make sure everything is in place. Thanks! 😊
> 
> Screenshot 2567-09-17 at 23 38 43

Ah ok, i think i see the issue. You are trying to run this on the GCP VM?
This helper class is for running the ETL on your own local machine instead of the GCP VM.

**Comment by hamcheezee** [comment]
> Ah ok, i think i see the issue. You are trying to run this on the GCP VM?
> This helper class is for running the ETL on your own local machine instead of the GCP VM.

Oh, I see! My mistake 😱.

**Review by satish-a0 — CHANGES_REQUESTED** [review]
As communicated clearly in the previous meetings, it's a violation of data usage agreement to run anything on local.

**Comment by brandantck** [comment]
> As communicated clearly in the previous meetings, it's a violation of data usage agreement to run anything on local.

sorry let me close this ticket then

**Pull request closed without merging**
