### PR TITLE
[Final] Load source_to_concept_map Table

### PR DESCRIPTION
**Pull request by satish-a0**
_This Pull Request will document changes to the `source_to_concept_map` table as Vocabulary team keeps updating us with the data._

### Version History

| Version   | Date  | Schemas
| -------- | ------- | --------
| v1  | 30th Sept 2024    | omop_sqldev_schema, omop_pydev_schema
| v2  | 8th Oct 2024    | omop_sqldev_schema
| v3  | 31st Oct 2024    | omop_sqldev_schema
| v3b  | 4th Nov 2024    | omop_etl_schema
| v3c  | 6th Nov 2024    | omop_etl_schema

#### - v1
image

### CODE REVIEW

**Comment by crabcakeworld** [comment]
v2
Add 8 more custom mapping vocabularies
Also changed the names of previous 3 custom mapping vocabulary names
[Source To Concept Mapping.xlsx](https://github.com/user-attachments/files/17273057/Source.To.Concept.Mapping.xlsx)


<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/QIBB41~1.YAN/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/QIBB41~1.YAN/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">


Source   table | Source table field | source_vocabulary_id
-- | -- | --
pre_op__char | gender | SG_PASAR_PREOP_CHAR_GENDER
pre_op__char | race | SG_PASAR_PREOP_CHAR_RACE
intra_op__drug_drug | drug_name | SG_PASAR_INTRAOP_DRUG_DRUG
intra_op__drug_med | medication_name | SG_PASAR_INTRAOP_DRUG_MED
post_op__labs_all | gen_lab_lab_resulted_order_test_description | SG_PASAR_POSTOP_LABS_ALL
post_op__info | order_name | SG_PASAR_POSTOP_INFO
pre_op__lab | preop_lab_test_description | SG_PASAR_PREOP_LAB
intra_op__operation | surgical_specialty | SG_PASAR_INTRAOP_OPERATION_SPECIALTY
intra_op__aims_vitals | vitalcode | SG_PASAR_INTRAOP_AIMS_VITALS
pre_op__char | allergy_information | SG_PASAR_PREOP_CHAR_ALLERGY
intra_op__nur_vitals | document_item_name | SG_PASAR_INTRAOP_NUR_VITALS



</body>

</html>

**Comment by satish-a0** [comment]
@crabcakeworld It looks like for the exact source_code, source_vocabulary_id there are different target_concept_id's present. Example below and the codes attached [stcm_duplicates.csv](https://github.com/user-attachments/files/17348672/stcm_duplicates.csv). Please suggest on how to handle choose the required standard concept id.

image

**Comment by crabcakeworld** [comment]
[Source To Concept Mapping.xlsx](https://github.com/user-attachments/files/17581459/Source.To.Concept.Mapping.xlsx)

**Comment by crabcakeworld** [comment]
v3
Following vocabularies are included

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/QIBB41~1.YAN/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/QIBB41~1.YAN/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">


Source   table | Source table field | source_vocabulary_id
-- | -- | --
pre_op__char | gender | SG_PASAR_PREOP_CHAR_GENDER
pre_op__char | race | SG_PASAR_PREOP_CHAR_RACE
intra_op__drug_drug | drug_name | SG_PASAR_INTRAOP_DRUG_DRUG
intra_op__drug_med | medication_name | SG_PASAR_INTRAOP_DRUG_MED
post_op__labs_all | gen_lab_lab_resulted_order_test_description | SG_PASAR_POSTOP_LABS_ALL
post_op__info | order_name | SG_PASAR_POSTOP_INFO
pre_op__lab | preop_lab_test_description | SG_PASAR_PREOP_LAB
intra_op__operation | surgical_specialty | SG_PASAR_INTRAOP_OPERATION_SPECIALTY
intra_op__aims_vitals | vitalcode | SG_PASAR_INTRAOP_AIMS_VITALS
pre_op__char | allergy_information | SG_PASAR_PREOP_CHAR_ALLERGY
intra_op__nur_vitals | document_item_name | SG_PASAR_INTRAOP_NUR_VITALS
post_op__pacu | pacu_item_name | SG_PASAR_POSTOP_PACU
post_op__renal | crrt_type, dialysis_modality | SG_PASAR_POSTOP_RENAL
post_op__clin_doc | postop_clindoc_item_name | SG_PASAR_POSTOP_CLIN_DOC
post_op__lab | postop_lab_test_desc | SG_PASAR_POSTOP_LAB
pre_op__radiology | procedure_name | SG_PASAR_PREOP_RADIOLOGY
intra_op__operation | procedure_code | SG_PASAR_INTRAOP_SURGERY



</body>

</html>

**Comment by crabcakeworld** [comment]
[Source To Concept Mapping.xlsx](https://github.com/user-attachments/files/17609393/Source.To.Concept.Mapping.xlsx)

V3b - new vocabularies have been added.

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/QIBB41~1.YAN/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/QIBB41~1.YAN/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">


Source   table | Source table field | source_vocabulary_id
-- | -- | --
pre_op__char | gender | SG_PASAR_PREOP_CHAR_GENDER
pre_op__char | race | SG_PASAR_PREOP_CHAR_RACE
intra_op__drug_drug | drug_name | SG_PASAR_INTRAOP_DRUG_DRUG
intra_op__drug_med | medication_name | SG_PASAR_INTRAOP_DRUG_MED
post_op__labs_all | gen_lab_lab_resulted_order_test_description | SG_PASAR_POSTOP_LABS_ALL
post_op__info | order_name | SG_PASAR_POSTOP_INFO
pre_op__lab | preop_lab_test_description | SG_PASAR_PREOP_LAB
intra_op__operation | surgical_specialty | SG_PASAR_INTRAOP_OPERATION_SPECIALTY
intra_op__aims_vitals | vitalcode | SG_PASAR_INTRAOP_AIMS_VITALS
pre_op__char | allergy_information | SG_PASAR_PREOP_CHAR_ALLERGY
intra_op__nur_vitals | document_item_name | SG_PASAR_INTRAOP_NUR_VITALS
post_op__pacu | pacu_item_name | SG_PASAR_POSTOP_PACU
post_op__renal | crrt_type, dialysis_modality | SG_PASAR_POSTOP_RENAL
post_op__clin_doc | postop_clindoc_item_name | SG_PASAR_POSTOP_CLIN_DOC
post_op__lab | postop_lab_test_desc | SG_PASAR_POSTOP_LAB
pre_op__radiology | procedure_name | SG_PASAR_PREOP_RADIOLOGY
intra_op__operation | procedure_code | SG_PASAR_INTRAOP_SURGERY
pre_op__char | admission_type | SG_PASAR_PREOP_ADMISSION
post_op__icu | endotracheal_tube_insertion_date | SG_PASAR_POSTOP_ENDOTRACHEAL_TUBE
post_op__icu | tracheostomy_tube_insertion_date | SG_PASAR_POSTOP_TRACHEOSTOMY_TUBE
pre_op__risk_index | high_risk_op | SG_PASAR_PREOP_RISK
pre_op__risk_index | h_o_ihd | SG_PASAR_PREOP_RISK
pre_op__risk_index | h_o_chf | SG_PASAR_PREOP_RISK
pre_op__risk_index | h_o_cva | SG_PASAR_PREOP_RISK
pre_op__risk_index | dm_on_insulin | SG_PASAR_PREOP_RISK
pre_op__risk_index | hypertension | SG_PASAR_PREOP_RISK
pre_op__risk_index | history_of_osa | SG_PASAR_PREOP_RISK
pre_op__risk_index | loud_snoring | SG_PASAR_PREOP_RISK
pre_op__risk_index | daytime_tiredness | SG_PASAR_PREOP_RISK
pre_op__risk_index | apnoea | SG_PASAR_PREOP_RISK
pre_op__risk_index | history_of_hypertension | SG_PASAR_PREOP_RISK
pre_op__risk_index | history_of_motion_sickness | SG_PASAR_PREOP_RISK
pre_op__risk_index | cpap_use | SG_PASAR_PREOP_RISK
pre_op__char | height | SG_PASAR_PREOP_VITAL
pre_op__char | weight | SG_PASAR_PREOP_VITAL
pre_op__char | bmi | SG_PASAR_PREOP_VITAL
pre_op__char | systolic_bp | SG_PASAR_PREOP_VITAL
pre_op__char | diastolic_bp | SG_PASAR_PREOP_VITAL
pre_op__char | heart_rate | SG_PASAR_PREOP_VITAL
pre_op__char | o2_saturation | SG_PASAR_PREOP_VITAL
pre_op__char | o2_supplementaries | SG_PASAR_PREOP_VITAL
pre_op__char | temperature | SG_PASAR_PREOP_VITAL
pre_op__char | pain_score | SG_PASAR_PREOP_VITAL



</body>

</html>

**Review by csafreen — APPROVED** [review]

**Pull request merged**
